_security_logout:
    path:  /logout
AntonShopBundle_homepage:
    path:     /
    defaults: { _controller: "AntonShopBundle:Page:index" }
    requirements:
         methods:  GET
AntonShopBundle_login:
    path:   /login
    defaults: { _controller: "AntonShopBundle:Page:login" }
    requirements:
         methods:  GET
AntonShopBundle_signup:
    path:  /signup
    defaults: { _controller: "AntonShopBundle:Registration:register" }
    requirements:
        methods:  GET|POST