# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Anton\ShopBundle\Entity\User:
            algorithm: md5
            encode_as_base64: true
            iterations: 0
    role_hierarchy:
            ROLE_MODERATOR:    ROLE_USER
            ROLE_ADMIN:       [ROLE_MODERATOR, ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
    providers:
            database_users:
                id: app.user_provider

    firewalls:
        dev:
                    pattern: ^/(_(profiler|wdt)|css|images|js)/
                    security: false

        main:
            anonymous:
            provider: database_users
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path:   /logout
                target: /
    access_control:
             - { path: ^/management/products, roles: ROLE_MODERATOR }
             - { path: ^/management/users, roles: ROLE_ADMIN }
             - { path: ^/category/, roles: ROLE_MODERATOR }
             - { path: ^/product/page, roles: ROLE_USER }
             - { path: ^/product, roles: ROLE_MODERATOR }
             - { path: ^/catalogue, roles: ROLE_USER }
             - { path: ^/recovery, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # disables authentication for assets and the profiler, adapt it according to your needs


            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
