# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Anton\ShopBundle\Entity\User:
            algorithm: md5
            encode-as-base64: true
            iterations: 10
    role_hierarchy:
            ROLE_MODERATOR:    ROLE_USER
            ROLE_ADMIN:       [ROLE_MODERATOR, ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
    providers:
            our_db_provider:
                entity:
                    class: AntonShopBundle:User
                    property: username

    firewalls:
        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.api_token_authenticator
            form_login:
                login_path: security_login
                check_path: security_login
            logout:
                path:   /logout
                target: /

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
