# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Anton\ShopBundle\Entity\User:
            algorithm: md5
            encode-as-base64: true
            iterations: 10

    providers:
            our_db_provider:
                entity:
                    class: AntonShopBundle:User
                    property: username

    firewalls:
        main:
                            pattern:    ^/login
                            http_basic: ~
                            provider: our_db_provider
                            logout: true
                            security: true
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html