# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
      app.user_provider:
            class: Anton\ShopBundle\Entity\UserProvider
            arguments: ["@doctrine.orm.entity_manager"]
      app.form_login_authenticator:
            class: Anton\ShopBundle\Security\FormLoginAuthenticator
            autowire: true
            arguments: ["@router","@security.password_encoder"]
      app.last_login:
              class: Anton\ShopBundle\EventListener\LastLoginTime
              arguments: ["@doctrine.orm.entity_manager"]
              tags:
                  - { name: kernel.event_subscriber }
      #service_name:
       # class: AppBundle\Directory\ClassName
       # arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
